// livro-servidor/clientes/livros-react/src/LivroLista.js
import { useState, useEffect } from 'react';
import { ControleLivro } from './controle/ControleLivros';
import { ControleEditora } from './controle/ControleEditora';

const LivroLista = () => {
  const controleLivro = new ControleLivro();
  const controleEditora = new ControleEditora();

  const [livros, setLivros] = useState([]);
  const [carregado, setCarregado] = useState(false);

  const excluir = async (codigo) => {
    await controleLivro.excluir(codigo);
    setCarregado(false);
  };

  useEffect(() => {
    controleLivro.obterLivros()
      .then((result) => {
        setLivros(result);
        setCarregado(true);
      });
  }, [carregado]);

  const LinhaLivro = ({ livro }) => {
    const nomeEditora = controleEditora.getNomeEditora(livro.codEditora);
    return (
      <tr>
        <td>{livro.titulo} <button className="btn btn-danger btn-sm" onClick={() => excluir(livro.codigo)}>Excluir</button></td>
        <td>{nomeEditora}</td>
        <td>{livro.resumo}</td>
        <td>
          <ul>
            {livro.autores.map((autor, index) => <li key={index}>{autor}</li>)}
          </ul>
        </td>
      </tr>
    );
  };

  return (
    <main className="container mt-4">
      <h1>Catálogo de Livros</h1>
      <table className="table">
        <thead className='bg-dark text-white'>
          <tr>
            <th>Título</th>
            <th>Editora</th>
            <th>Resumo</th>
            <th>Autores</th>
          </tr>
        </thead>
        <tbody>
          {livros.map((livro, index) => <LinhaLivro key={index} livro={livro} />)}
        </tbody>
      </table>
    </main>
  );
};

export default LivroLista;

// livro-servidor/clientes/livros-angular/src/app/livro-lista/livro-lista.component.ts
import { Component, OnInit } from '@angular/core';
import { Editora } from '../editora';
import { Livro } from '../livro';
import { ControleEditoraService } from '../controle-editora.service';
import { ControleLivrosService } from '../controle-livros.service';

@Component({
  selector: 'app-livro-lista',
  templateUrl: './livro-lista.component.html',
  styleUrls: ['./livro-lista.component.css']
})
export class LivroListaComponent implements OnInit {
  public editoras: Array<Editora> = [];
  public livros: Array<Livro> = [];

  constructor(
    private servEditora: ControleEditoraService,
    private servLivros: ControleLivrosService
  ) { }

  async ngOnInit(): Promise<void> {
    this.editoras = this.servEditora.getEditoras();
    this.servLivros.obterLivros().then(livros => {
      this.livros = livros;
    });
  }

  excluir = (codigoLivro: string) => {
    this.servLivros.excluir(codigoLivro)
      .then(() => {
        return this.servLivros.obterLivros();
      })
      .then(livros => {
        this.livros = livros;
      });
  }

  obterNome = (codEditora: number) => {
    return this.servEditora.getNomeEditora(codEditora);
  }
}

<main class="container mt-4">
    <h1 class="mb-4">Catálogo</h1>
    <table class="table table-striped">
      <thead class="thead-dark">
        <tr>
          <th>Código</th>
          <th>Título</th>
          <th>Editora</th>
          <th>Autores</th>
        </tr>
      </thead>
      <tbody>
        <tr *ngFor="let livro of livros">
          <td>{{ livro.codigo }}</td>
          <td>{{ livro.titulo }}
            <button class="btn btn-danger btn-sm ml-2" (click)="excluir(livro.codigo)">Excluir</button>
          </td>
          <td>{{ obterNome(livro.codEditora) }}</td>
          <td>
            <ul>
              <li *ngFor="let autor of livro.autores">{{ livro.autores}}</li>
            </ul>
          </td>
        </tr>
      </tbody>
    </table>
  </main>
