// livros-react/src/LivroDados.js
import React, { useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { Livro } from './modelo/Livro';
import { ControleLivro } from './controle/ControleLivros';
import { ControleEditora } from './controle/ControleEditora';

const LivroDados = () => {
  const controleLivro = new ControleLivro();
  const controleEditora = new ControleEditora();

  const opcoes = controleEditora.getEditoras().map((editora) => ({
    value: editora.codEditora,
    text: editora.nome,
  }));

  const [titulo, setTitulo] = useState('');
  const [resumo, setResumo] = useState('');
  const [autores, setAutores] = useState('');
  const [codEditora, setCodEditora] = useState(opcoes[0].value);

  const navigate = useNavigate();

  const tratarCombo = (event) => {
    setCodEditora(Number(event.target.value));
  };

  const incluir = (event) => {
    event.preventDefault();
    const livro = new Livro(0, codEditora, titulo, resumo, autores.split('\n'));
    controleLivro.incluir(livro);
    navigate('/');
  };

  return (
    <main className="container mt-4">
      <h1>Dados do Livro</h1>
      <form onSubmit={incluir}>
        <div className="form-group">
          <label>Título</label>
          <input type="text" className="form-control" value={titulo} onChange={(e) => setTitulo(e.target.value)} />
        </div>
        <div className="form-group">
          <label>Resumo</label>
          <textarea className="form-control" value={resumo} onChange={(e) => setResumo(e.target.value)} />
        </div>
        <div className="form-group">
          <label>Editora</label>
          <select className="form-control" value={codEditora} onChange={tratarCombo}>
            {opcoes.map((opcao, index) => (
              <option key={index} value={opcao.value}>{opcao.text}</option>
            ))}
          </select>
        </div>
        <div className="form-group">
          <label>Autores (um por linha)</label>
          <textarea className="form-control" value={autores} onChange={(e) => setAutores(e.target.value)} />
        </div>
        <button type="submit" className="btn btn-primary">Incluir</button>
      </form>
    </main>
  );
};

export default LivroDados;

// livros-angular/src/app/livro-dados/livro-dados.component.ts
import { Component, OnInit } from '@angular/core';
import { Router } from '@angular/router';
import { Livro } from '../livro';
import { Editora } from '../editora';
import { ControleEditoraService } from '../controle-editora.service';
import { ControleLivrosService } from '../controle-livros.service';

@Component({
  selector: 'app-livro-dados',
  templateUrl: './livro-dados.component.html',
  styleUrls: ['./livro-dados.component.css']
})
export class LivroDadosComponent implements OnInit {
  public livro: Livro = new Livro(0, 0, '', '', []);
  public autoresForm: string = '';
  public editoras: Array<Editora> = [];

  constructor(
    private servEditora: ControleEditoraService,
    private servLivros: ControleLivrosService,
    private router: Router
  ) { }

  ngOnInit(): void {
    this.editoras = this.servEditora.getEditoras();
  }

  incluir = () => {
    this.livro.autores = this.autoresForm.split('\n'); 
    this.servLivros.incluir(this.livro);
    this.router.navigateByUrl('/lista'); 
  }
}

<main class="container">
    <h1>Dados do Livro</h1>
    <form (submit)="incluir()" ngNativeValidate>
      <div class="form-group">
        <label for="titulo">Título:</label>
        <input type="text" class="form-control" id="titulo" [(ngModel)]="livro.titulo" name="titulo" required>
      </div>
      <div class="form-group">
        <label for="resumo">Resumo:</label>
        <textarea class="form-control" id="resumo" [(ngModel)]="livro.resumo" name="resumo"></textarea>
      </div>
      <div class="form-group">
        <label for="editora">Editora:</label>
        <select class="form-control" id="editora" [(ngModel)]="livro.codEditora" name="editora" required>
            <option *ngFor="let editora of editoras" [value]="editora.codEditora">{{editora.nome}}</option>
        </select>
      </div>
      <div class="form-group">
        <label for="autoresForm">Autores (separados por linha):</label>
        <textarea class="form-control" id="autoresForm" [(ngModel)]="autoresForm" name="autoresForm"></textarea>
      </div>
      <button type="submit" class="btn btn-primary">Incluir Livro</button>
    </form>
  </main>
